export const FgRed = '\x1b[31m'
export const FgYellow = '\x1b[33m'
export const Reset = '\x1b[0m'
export const FgGreen = '\x1b[32m'
export const FgLightGreen = '\x1b[92m'
export const FgBlue = '\x1b[34m'
